import { ExcelSeedItem } from "./excelMenuData";

export const tariniMenuItems: ExcelSeedItem[] = [
  // SOUPS
  {
    id: "tr_sp1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_soups",
    name: "Mixed Veg Soup",
    description: "Wholesome clear broth simmered with garden-fresh winter vegetables and delicate herbs.",
    price: 89,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_sp2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_soups",
    name: "Manchow Soup",
    description: "Classic Indo-Chinese spicy dark broth loaded with minced vegetables, served with crispy fried noodles.",
    price: 99,
    image_url: "https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_sp3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_soups",
    name: "Hot & Sour Soup",
    description: "Tangy and fiery broth spiked with red chilies, white pepper, bamboo shoots, and finely diced mushrooms.",
    price: 99,
    image_url: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_sp4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_soups",
    name: "Sweet Corn Soup",
    description: "Velvety comfort soup made with crushed golden American sweet corn kernels and delicate seasoning.",
    price: 99,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_sp5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_soups",
    name: "Lemon Coriander Soup",
    description: "Refreshing aromatic clear soup infused with fresh green coriander stems and a lively squeeze of lemon.",
    price: 99,
    image_url: "https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_sp6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_soups",
    name: "Veg Noodles Soup",
    description: "Steaming hot broth brimming with silky noodles, crunchy cabbage, carrots, and spring onions.",
    price: 99,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_sp7",
    brand_id: "brand_tarini",
    category_id: "cat_tr_soups",
    name: "Veg Clear Soup",
    description: "Light, restorative simmered vegetable broth accented with crushed black peppercorns.",
    price: 89,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_sp8",
    brand_id: "brand_tarini",
    category_id: "cat_tr_soups",
    name: "Chicken Manchow Soup",
    description: "Robust spicy broth simmered with tender shredded chicken, garlic, egg drops, topped with crunchy noodles.",
    price: 109,
    image_url: "https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_sp9",
    brand_id: "brand_tarini",
    category_id: "cat_tr_soups",
    name: "Chicken Hot & Sour Soup",
    description: "Bold chicken soup striking the perfect balance of chili heat and dark vinegar tang.",
    price: 109,
    image_url: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_sp10",
    brand_id: "brand_tarini",
    category_id: "cat_tr_soups",
    name: "Chicken Sweet Corn Soup",
    description: "Silky, hearty chicken soup folded with sweet golden corn and beaten egg ribbons.",
    price: 109,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },

  // VEG STARTERS
  {
    id: "tr_vs1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Veg 65",
    description: "Crispy fried vegetable florets tossed with curry leaves, cracked mustard seeds, and Andhra red chili paste.",
    price: 129,
    image_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vs2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Paneer 65",
    description: "Fresh cottage cheese cubes fried till golden, spiced with fiery South-Indian masala and roasted curry leaves.",
    price: 169,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vs3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Paneer Manchurian",
    description: "Soft paneer tossed in savory garlic, ginger, and scallion dark soy glaze.",
    price: 169,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vs4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Paneer Chilli",
    description: "Crispy paneer tossed in wok with crunchy bell peppers, onions, and green chilies.",
    price: 169,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vs5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Paneer Majestic",
    description: "Crispy paneer fingers infused with turmeric, green chili, and rich spiced curd emulsion.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vs6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Paneer Hot Garlic",
    description: "Succulent paneer wok-tossed in robust crushed garlic and smoky hot chili oil.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vs7",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Mushroom 65",
    description: "Plump button mushrooms batter-fried and tossed in spiced 65 masala with crunchy onions.",
    price: 149,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vs8",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Mushroom Chilli",
    description: "Stir-fried button mushrooms with capsicum and spicy soy reduction.",
    price: 159,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vs9",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Mushroom & Baby Corn",
    description: "Crisp golden baby corn and earthy mushrooms wok-sizzled with green peppers.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vs10",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Baby Corn Chilli",
    description: "Crunchy baby corn sticks tossed in zesty sweet-spicy chili garlic sauce.",
    price: 159,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vs11",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Crispy Corn",
    description: "Fried sweet corn kernels seasoned with chaat masala, lemon juice, diced onions and cilantro.",
    price: 149,
    image_url: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vs12",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Corn Salt & Pepper",
    description: "Golden corn tossed dry in freshly ground black pepper and scallions.",
    price: 159,
    image_url: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vs13",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_starters",
    name: "Cheese Balls",
    description: "Crispy crusted golden spheres bursting with melted spiced mozzarella and herbs.",
    price: 129,
    image_url: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },

  // NON-VEG STARTERS
  {
    id: "tr_nvs1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Chicken 65",
    description: "Bite-sized boneless chicken cubes marinated in red chili, yogurt, fried and tempered with curry leaves.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvs2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Chilli Chicken",
    description: "All-time favorite Indo-Chinese crispy chicken tossed with green chilies, onions and dark soy sauce.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvs3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Chicken Manchurian",
    description: "Crispy chicken morsels glazed in rich ginger-garlic and coriander sauce.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvs4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Pepper Chicken",
    description: "South Indian style chicken stir-fry dominated by crushed black Malabar peppercorns and curry leaves.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvs5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Chicken Salt & Pepper",
    description: "Crisp chicken pieces sautéed with crushed sea salt, five-spice pepper, and spring garlic.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvs6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Chicken Mongolian",
    description: "Tender chicken strips wok-tossed in savory brown Mongolian sauce with ginger and scallions.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvs7",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Chicken 555",
    description: "Crisp fried chicken fingers tossed in spicy yogurt, crushed red chilies, and fried cashews.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvs8",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Lemon Chicken",
    description: "Crispy chicken glazed in a luscious citrusy lemon and ginger glaze with honey notes.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvs9",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Chicken Hot Garlic",
    description: "Crispy boneless chicken tossed in intense spicy garlic chili sauce.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvs10",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Chicken Majestic",
    description: "Hyderabadi style dry chicken strips cooked with green chilies, mint, yogurt and aromatic spices.",
    price: 169,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvs11",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Chicken Lollipop",
    description: "Frenched chicken winglets deep-fried with crispy spiced coating, served with hot garlic dipping sauce.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1527477321055-436158a2b00d?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvs12",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Dragon Chicken",
    description: "Crispy chicken strips wok-tossed in fiery red chili, roasted cashews, and bell peppers.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvs13",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Tarini's Spl Kung Pao Chicken",
    description: "Chef's signature spicy chicken sautéed with roasted peanuts, dried red chilies, and Sichuan peppercorns.",
    price: 229,
    image_url: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvs14",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Tarini's Spl Toriyaki Chicken",
    description: "Pan-glazed tender chicken in glossy sweet teriyaki reduction with sesame garnish.",
    price: 229,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvs15",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Tarini's Spl Poluchutt Chicken",
    description: "Special Kerala-style spicy roasted chicken wrapped in aromatic charred banana leaf.",
    price: 229,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvs16",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Mutton Ghee Roast",
    description: "Tender boneless mutton slow-cooked in pure fragrant desi ghee and freshly roasted coastal spices.",
    price: 299,
    image_url: "https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvs17",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Loose Prawns",
    description: "Fresh coastal prawns batter-fried crisp and tossed with curry leaves, cracked pepper, and green chilies.",
    price: 279,
    image_url: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvs18",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Chilli Prawns",
    description: "Juicy prawns stir-fried in a spicy Indo-Chinese chili sauce with onion petals and capsicum.",
    price: 289,
    image_url: "https://images.unsplash.com/photo-1559742811-822873691df8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvs19",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Hot Garlic Prawns",
    description: "Prawns sautéed with crushed garlic and spicy chili paste in a rich savory coat.",
    price: 299,
    image_url: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvs20",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_starters",
    name: "Dragon Prawns",
    description: "Crisp golden fried prawns tossed in fiery red dragon sauce with crunchy roasted cashew nuts.",
    price: 299,
    image_url: "https://images.unsplash.com/photo-1559742811-822873691df8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },

  // TANDOORI / KEBAB VEG
  {
    id: "tr_tkv1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_veg",
    name: "Paneer Tikka (6pcs)",
    description: "Cottage cheese cubes marinated in yogurt, tandoori spices and mustard oil, grilled in the clay oven.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_tkv2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_veg",
    name: "Paneer Malai Tikka (6pcs)",
    description: "Mild and creamy paneer skewers marinated in heavy cream, cashew paste, and green cardamom.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_tkv3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_veg",
    name: "Paneer Achari Tikka (6pcs)",
    description: "Paneer cubes infused with pungent pickling spices, mustard oil, and roasted in tandoor.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_tkv4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_veg",
    name: "Paneer Hariyali Tikka (6pcs)",
    description: "Vibrant green paneer cubes coated in mint, fresh coriander, green chili and spinach marinade.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_tkv5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_veg",
    name: "Paneer Kalimirchi Tikka (6pcs)",
    description: "Charcoal-grilled paneer highlighted with freshly roasted crushed black peppercorns.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_tkv6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_veg",
    name: "Hara Bhara Kebab (6pcs)",
    description: "Crispy pan-seared spinach, green pea, and potato patties filled with roasted cumin and chaat masala.",
    price: 159,
    image_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_tkv7",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_veg",
    name: "Veg Seekh Kebab",
    description: "Minced spiced vegetables and herbs skewered and slow-roasted over fragrant charcoal embers.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_tkv8",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_veg",
    name: "Stuffed Mushroom Kebab",
    description: "Plump button mushrooms stuffed with spiced cheese and herb filling, roasted to perfection.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_tkv9",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_veg",
    name: "Tarini's Spl 5 Monkey Paneer Tikka (6pcs)",
    description: "Chef's secret 5-spice marinade on thick paneer cubes roasted with bell pepper and onion skewers.",
    price: 229,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_tkv10",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_veg",
    name: "Tarini's Spl 5 Monkey Paneer Dilkush (6pcs)",
    description: "Paneer layers stuffed with dry fruits and mint chutney, char-grilled with saffron cream.",
    price: 239,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },

  // TANDOORI / KEBAB NON-VEG
  {
    id: "tr_tkn1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_nonveg",
    name: "Tandoori Chicken - Half",
    description: "Classic bone-in chicken marinated in hung curd, Kashmiri red chili, and slow-roasted in clay tandoor.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_tkn2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_nonveg",
    name: "Tandoori Chicken - Full",
    description: "Whole whole-cut chicken slow-grilled in clay tandoor with aromatic garam masala and lemon butter.",
    price: 449,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_tkn3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_nonveg",
    name: "Tarini's Spl Tandoori Kebab",
    description: "Chef's signature combination tandoori kebab platter with spiced mint reduction.",
    price: 299,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_tkn4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_nonveg",
    name: "Chicken Mahal Kebab (6pcs)",
    description: "Royal Mughal style chicken kebabs marinated in saffron, almond paste, and subtle mace spice.",
    price: 239,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_tkn5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_nonveg",
    name: "Chicken Reshmi Kebab (6pcs)",
    description: "Silky melt-in-mouth chicken cubes marinated in egg white, cashew cream, and green cardamom.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_tkn6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_nonveg",
    name: "Chicken Hariyali Kebab (6pcs)",
    description: "Juicy chicken chunks wrapped in fresh mint, cilantro, and green chili paste char-grilled.",
    price: 229,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_tkn7",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_nonveg",
    name: "Chicken Tikka Kebab (6pcs)",
    description: "Spicy red tandoori marinated boneless chicken thighs grilled with capsicum and onion.",
    price: 239,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_tkn8",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_nonveg",
    name: "Chicken Lapeta Kebab (6pcs)",
    description: "Chicken pieces coated in a luscious spiced egg and cheese coat, grilled to tender perfection.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_tkn9",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_nonveg",
    name: "Chicken Tangdi Kebab (2pcs)",
    description: "Chicken drumsticks stuffed with minced chicken, cheese, and grilled over charcoal.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1527477321055-436158a2b00d?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_tkn10",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_nonveg",
    name: "Chicken Seekh Kebab (6pcs)",
    description: "Spiced minced chicken blended with coriander, mint and ginger skewered and fire-roasted.",
    price: 229,
    image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_tkn11",
    brand_id: "brand_tarini",
    category_id: "cat_tr_tandoori_nonveg",
    name: "Chicken Dilkush Kebab (6pcs)",
    description: "Delicate chicken parcels stuffed with seasoned paneer, dry fruits, and grilled with cheese topping.",
    price: 259,
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },

  // VEG CURRIES
  {
    id: "tr_vc1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Dal Fry",
    description: "Yellow lentils cooked smooth and tempered with cumin, garlic, tomatoes and fresh coriander.",
    price: 110,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vc2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Dal Tadka",
    description: "Homestyle yellow dal finished with double tadka of smoky desi ghee, whole red chilies, and hing.",
    price: 110,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vc3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Tarini's Spl Paneer Masala",
    description: "House special rich and spicy curry with paneer cubes in thick onion, tomato and cashew gravy.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vc4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Paneer Butter Masala",
    description: "Mild, creamy tomato gravy enriched with fresh butter, cashew cream, and fragrant kasuri methi.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vc5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Paneer Kadai",
    description: "Paneer cubes and crisp bell peppers tossed in spicy freshly pounded coriander seed kadai masala.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vc6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Paneer Lababdar",
    description: "Luscious grated and cubed paneer folded in creamy tomato-onion gravy with subtle sweet notes.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vc7",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Paneer Do Pyaza",
    description: "Paneer cooked with twice the quantity of sautéed crunchy onions in rich Mughlai masala.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vc8",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Paneer Kolhapuri",
    description: "Fiery Maharashtrian curry prepared with Kolhapuri red chili paste, roasted coconut and whole spices.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vc9",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Mix Veg Curry",
    description: "Assorted seasonal vegetables simmered in spiced onion-tomato gravy.",
    price: 159,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vc10",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Veg Kolhapuri",
    description: "Medley of garden vegetables cooked in spicy Kolhapuri red masala with desiccated coconut.",
    price: 169,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vc11",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Palak Paneer",
    description: "Fresh tender cottage cheese cubes simmered in velvety garlic-infused spinach puree.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vc12",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Paneer Tikka Masala",
    description: "Charcoal-grilled paneer tikka pieces submerged in rich, mildly spiced tomato cream gravy.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vc13",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Mushroom Masala",
    description: "Fresh button mushrooms simmered in thick roasted onion and tomato masala.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vc14",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Mushroom Kadai",
    description: "Button mushrooms and bell peppers tossed in freshly ground kadai spices.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vc15",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Mushroom Curry",
    description: "Comforting homestyle button mushroom gravy with aromatic garam masala.",
    price: 169,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vc16",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Mushroom Do Pyaza",
    description: "Mushrooms cooked with twice-added diced onions and whole spices.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vc17",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Kaju Curry",
    description: "Roasted golden cashew nuts simmered in royal creamy cashew-onion-tomato gravy.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vc18",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Hyderabad Corn Palak",
    description: "Sweet corn kernels simmered in garlic-tempered Hyderabadi spinach puree.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_vc19",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Spl Veg Diwani Handi",
    description: "Royal vegetable medley cooked in rich handi gravy with saffron and cashew paste.",
    price: 209,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_vc20",
    brand_id: "brand_tarini",
    category_id: "cat_tr_veg_curries",
    name: "Spl Veg Patiala",
    description: "Crispy stuffed papad rolls bathed in spicy Punjabi tomato-onion gravy.",
    price: 219,
    image_url: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },

  // NON-VEG CURRIES
  {
    id: "tr_nvc1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Egg Curry",
    description: "Boiled golden-fried eggs cooked in aromatic homestyle onion-tomato gravy.",
    price: 120,
    image_url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvc2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Egg Masala",
    description: "Eggs simmered in a thick roasted onion gravy with cracked black pepper and green chilies.",
    price: 130,
    image_url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvc3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Egg Bhurji",
    description: "Scrambled eggs stir-fried with chopped onions, tomatoes, green chilies, and fresh coriander.",
    price: 110,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvc4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Butter Chicken",
    description: "Tender tandoori chicken simmered in rich creamy tomato and butter gravy with kasuri methi.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Tarini's Spl Butter Chicken",
    description: "Chef's signature extra creamy butter chicken with shredded tandoori tikka and cashew glaze.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Special Chicken Lababdar",
    description: "Tender chicken cooked with grated cheese and cashew cream in a rich Mughlai sauce.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc7",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Chicken Kadai",
    description: "Chicken pieces tossed with freshly roasted coriander seeds and capsicum in spicy iron wok.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvc8",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Chicken Do Pyaza",
    description: "Succulent chicken simmered with generous caramelized onions and whole spices.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvc9",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Angara Chicken",
    description: "Smoky charcoal-infused fiery chicken gravy bursting with red chilies and cloves.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc10",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Punjabi Chicken Curry",
    description: "Dhaba style spicy chicken curry with robust garlic, ginger and whole roasted spices.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc11",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Telangana Chicken Curry",
    description: "Rustic South-Indian country chicken curry with curry leaves, poppy seeds, and fiery green chili.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc12",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Andhra Chicken Curry",
    description: "Famous Guntur chili and coconut based hot chicken curry with incredible regional depth.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc13",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Chicken Tikka Masala",
    description: "Char-grilled boneless chicken tikka cooked in rich, spiced tomato and cream gravy.",
    price: 229,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc14",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Tarini's Spl Chicken Rara",
    description: "Chicken pieces slow-cooked together with rich minced chicken keema in fragrant brown masala.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc15",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Tarini's Spl Murg Masala Curry",
    description: "Grand banquet style chicken curry cooked with boiled eggs, almonds and aromatic Mughlai spices.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvc16",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Tarini's Spl Chicken XXX",
    description: "Chef's extra fiery hot chicken curry crafted with ghost pepper and regional roasted chilies.",
    price: 279,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc17",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Boneless Chicken Curry",
    description: "Pure tender boneless chicken cuts simmered in velvety spiced onion-tomato curry.",
    price: 279,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvc18",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Mutton Curry",
    description: "Tender goat meat slow-cooked on bone with whole spices until deeply flavorful and rich.",
    price: 279,
    image_url: "https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc19",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Mutton Rogan Josh",
    description: "Kashmiri delicacy slow-cooked with aromatic ratanjot, fennel powder, ginger, and yogurt.",
    price: 299,
    image_url: "https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc20",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Mutton Andhra Curry",
    description: "Spicy Andhra mutton curry cooked with fiery Guntur red chilies and fresh coconut milk.",
    price: 299,
    image_url: "https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc21",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Special Mutton Curry",
    description: "Chef's premium mutton preparation with slow-braised shank cuts and saffron essence.",
    price: 339,
    image_url: "https://images.unsplash.com/photo-1545247181-516773cae754?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc22",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Prawns Masala",
    description: "Fresh coastal prawns cooked in thick spiced onion-tomato gravy with curry leaf tempering.",
    price: 279,
    image_url: "https://images.unsplash.com/photo-1559742811-822873691df8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_nvc23",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Prawns Kadai",
    description: "Prawns wok-tossed with bell peppers, fresh ginger, and freshly crushed kadai spices.",
    price: 289,
    image_url: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_nvc24",
    brand_id: "brand_tarini",
    category_id: "cat_tr_nonveg_curries",
    name: "Prawns Do Pyaza",
    description: "Prawns cooked in savory gravy loaded with caramelized sweet shallots and herbs.",
    price: 299,
    image_url: "https://images.unsplash.com/photo-1559742811-822873691df8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },

  // BIRYANI
  {
    id: "tr_by1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Veg Biryani",
    description: "Fragrant aged basmati rice layered with garden vegetables, saffron milk, and aromatic spices.",
    price: 139,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_by2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Paneer Biryani",
    description: "Golden spiced paneer cubes slow-cooked in dum with saffron basmati rice and fried onions.",
    price: 189,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_by3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Egg Biryani",
    description: "Spiced roasted boiled eggs layered in fragrant dum basmati rice with mint and brown onions.",
    price: 139,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_by4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Chicken Dum Biryani (Single)",
    description: "Authentic Hyderabadi kacchi dum biryani portion for one, served with mirchi ka salan and raita.",
    price: 159,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_by5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Chicken Dum Biryani (Full)",
    description: "Generous full portion of slow-cooked Hyderabadi chicken dum biryani with two succulent chicken pieces.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_by6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Chicken 65 Biryani",
    description: "Aromatic dum biryani rice topped with a generous portion of spicy crispy Chicken 65.",
    price: 229,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_by7",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Chicken Tikka Biryani",
    description: "Smoky tandoori chicken tikka pieces folded into rich saffron basmati dum rice.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_by8",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Lollipop Biryani (4pcs)",
    description: "Crispy spicy chicken lollipops served on a bed of aromatic chicken dum biryani rice.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_by9",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Spl Chicken Dum Biryani",
    description: "Special chef's preparation with boneless chicken chunks, boiled egg, extra saffron and fried cashews.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_by10",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Spl Chicken Family Pack",
    description: "Jumbo family feast portion of chicken dum biryani served with chicken 65 starter, salan and raita.",
    price: 549,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_by11",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Fry Piece Biryani",
    description: "Andhra style deep-fried spiced chicken pieces served over steaming hot biryani rice.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_by12",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Mutton Biryani (Bone)",
    description: "Traditional kacchi mutton dum biryani with tender bone-in mutton pieces and long-grain basmati.",
    price: 289,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_by13",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Mutton Biryani (Boneless)",
    description: "Juicy boneless mutton cubes slow-cooked in dum with aromatic basmati rice.",
    price: 329,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_by14",
    brand_id: "brand_tarini",
    category_id: "cat_tr_biryani",
    name: "Prawns Biryani",
    description: "Succulent coastal prawns cooked with fragrant spices and layered in long-grain saffron basmati.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },

  // BREADS
  {
    id: "tr_br1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_breads",
    name: "Tandoori Roti",
    description: "Whole wheat flatbread baked crisp in clay tandoor.",
    price: 25,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_br2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_breads",
    name: "Butter Roti",
    description: "Tandoori whole wheat roti brushed with pure melted butter.",
    price: 40,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_br3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_breads",
    name: "Plain Naan",
    description: "Traditional refined flour leavened bread baked in the clay oven.",
    price: 35,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_br4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_breads",
    name: "Butter Naan",
    description: "Soft and flaky tandoori naan brushed generously with melted butter.",
    price: 45,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_br5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_breads",
    name: "Garlic Naan",
    description: "Tandoori naan topped with roasted minced garlic, fresh coriander, and butter.",
    price: 59,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_br6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_breads",
    name: "Pudina Paratha",
    description: "Layered tandoori paratha infused with dried mint leaves and butter.",
    price: 59,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_br7",
    brand_id: "brand_tarini",
    category_id: "cat_tr_breads",
    name: "Laccha Paratha",
    description: "Multi-layered crispy whole wheat paratha baked in tandoor.",
    price: 59,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_br8",
    brand_id: "brand_tarini",
    category_id: "cat_tr_breads",
    name: "Kulcha - Plain",
    description: "Soft leavened North Indian flatbread with sesame and coriander.",
    price: 59,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_br9",
    brand_id: "brand_tarini",
    category_id: "cat_tr_breads",
    name: "Kulcha - Paneer",
    description: "Crispy tandoor-baked kulcha stuffed with spiced cottage cheese filling.",
    price: 79,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },

  // PULAVS
  {
    id: "tr_pl1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_pulavs",
    name: "Chicken Pulav",
    description: "Subtly spiced basmati rice simmered with tender chicken cuts and whole garam masala.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_pl2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_pulavs",
    name: "Kodi Vepudu Pulav",
    description: "Famous Telugu specialty spiced chicken fry served over aromatic seasoned pulav rice.",
    price: 199,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_pl3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_pulavs",
    name: "Prawns Pulav",
    description: "Delicate fragrant basmati pulav cooked with sweet coastal prawns and fried onions.",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },

  // RICE
  {
    id: "tr_rc1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_rice",
    name: "Jeera Rice",
    description: "Long-grain basmati rice tempered with roasted cumin seeds and desi ghee.",
    price: 99,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_rc2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_rice",
    name: "Steam Rice",
    description: "Fluffy steamed long-grain basmati rice.",
    price: 89,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_rc3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_rice",
    name: "Pudina Rice",
    description: "Basmati rice tossed with fresh fragrant mint puree, fried cashews, and cloves.",
    price: 109,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_rc4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_rice",
    name: "Tomato Rice",
    description: "South Indian style spiced tangy tomato rice tempered with mustard and curry leaves.",
    price: 109,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_rc5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_rice",
    name: "Sambar Rice",
    description: "Classic South Indian comfort rice cooked in lentil vegetable sambar with ghee.",
    price: 129,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_rc6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_rice",
    name: "Sambar Rice with Fry Curry",
    description: "Comforting piping hot sambar rice accompanied by crispy potato/veg fry.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_rc7",
    brand_id: "brand_tarini",
    category_id: "cat_tr_rice",
    name: "Curd Rice",
    description: "Cool creamy seasoned curd rice tempered with mustard, ginger, green chilies and pomegranate.",
    price: 99,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },

  // CHINESE VEG
  {
    id: "tr_cv1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_chinese_veg",
    name: "Veg Fried Rice / Noodles",
    description: "Wok-tossed basmati rice or noodles with crisp shredded cabbage, carrots and spring onions.",
    price: 129,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_cv2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_chinese_veg",
    name: "Veg Schezwan Rice / Noodles",
    description: "Spicy wok-tossed rice or noodles with fiery Schezwan chili paste and garlic.",
    price: 139,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_cv3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_chinese_veg",
    name: "Paneer Fried Rice / Noodles",
    description: "Stir-fried rice or noodles with golden paneer cubes, vegetables and soy sauce.",
    price: 149,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_cv4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_chinese_veg",
    name: "Manchurian Fried Rice / Noodles",
    description: "Fried rice or noodles served mixed with delicious crispy vegetable Manchurian balls.",
    price: 159,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },
  {
    id: "tr_cv5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_chinese_veg",
    name: "Mix Veg Fried Rice / Noodles",
    description: "Loaded combination of baby corn, mushroom, paneer and garden greens in wok rice/noodles.",
    price: 169,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_cv6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_chinese_veg",
    name: "Veg Hong Kong Rice / Noodles",
    description: "Sweet and spicy Hong Kong style wok preparation with dried chilies and sesame.",
    price: 169,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },

  // CHINESE NON-VEG
  {
    id: "tr_cnv1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_chinese_nonveg",
    name: "Egg Fried Rice / Noodles",
    description: "Classic street-style scrambled egg wok-fried rice or noodles with scallions and soy.",
    price: 139,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_cnv2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_chinese_nonveg",
    name: "Chicken Fried Rice / Noodles",
    description: "Juicy chicken bits, scrambled egg, and garden vegetables tossed with basmati or noodles.",
    price: 149,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_cnv3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_chinese_nonveg",
    name: "Schezwan Chicken Rice / Noodles",
    description: "Fiery Schezwan spiced chicken rice or noodles with garlic and red chili flakes.",
    price: 159,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },
  {
    id: "tr_cnv4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_chinese_nonveg",
    name: "Chicken Hong Kong Rice / Noodles",
    description: "Sweet and spicy Hong Kong style chicken tossed with crispy cashews and vegetables.",
    price: 169,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 0
  },
  {
    id: "tr_cnv5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_chinese_nonveg",
    name: "Chicken Triple Schezwan Rice / Noodles",
    description: "Famous triple combination of Schezwan rice, fried noodles, and chicken Manchurian gravy.",
    price: 179,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80",
    is_veg: 0,
    is_featured: 1
  },

  // RAITA & SIDES
  {
    id: "tr_rt1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_raita",
    name: "Raita",
    description: "Cool whipped spiced curd with roasted cumin and mint.",
    price: 49,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_rt2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_raita",
    name: "Mix Veg Raita",
    description: "Chilled yogurt mixed with diced cucumber, onions, tomatoes and green chilies.",
    price: 59,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_rt3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_raita",
    name: "Boondi Raita",
    description: "Crispy chickpea flour boondi soaked in seasoned cumin yogurt.",
    price: 59,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_rt4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_raita",
    name: "Green Salad",
    description: "Sliced cucumber, carrots, tomatoes, onions, lemon wedges and green chilies.",
    price: 49,
    image_url: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_rt5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_raita",
    name: "Onion Salad",
    description: "Sliced crisp red onions with chat masala and lemon wedge.",
    price: 39,
    image_url: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_rt6",
    brand_id: "brand_tarini",
    category_id: "cat_tr_raita",
    name: "Masala Papad",
    description: "Crispy roasted tandoori papad topped with chopped onion, tomato, coriander and chaat masala.",
    price: 25,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 1
  },

  // SOFT DRINKS
  {
    id: "tr_sd1",
    brand_id: "brand_tarini",
    category_id: "cat_tr_softdrinks",
    name: "Thumbs Up",
    description: "Chilled fizzy Thums Up bottle/can.",
    price: 20,
    image_url: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_sd2",
    brand_id: "brand_tarini",
    category_id: "cat_tr_softdrinks",
    name: "Sprite",
    description: "Chilled lemon-lime Sprite bottle/can.",
    price: 20,
    image_url: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_sd3",
    brand_id: "brand_tarini",
    category_id: "cat_tr_softdrinks",
    name: "Coca Cola",
    description: "Chilled classic Coca Cola bottle/can.",
    price: 25,
    image_url: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_sd4",
    brand_id: "brand_tarini",
    category_id: "cat_tr_softdrinks",
    name: "Maaza",
    description: "Refreshing sweet Alphonso mango pulpy drink.",
    price: 20,
    image_url: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  },
  {
    id: "tr_sd5",
    brand_id: "brand_tarini",
    category_id: "cat_tr_softdrinks",
    name: "Water Bottle (1L)",
    description: "Pure packaged packaged mineral drinking water bottle.",
    price: 20,
    image_url: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&auto=format&fit=crop&q=80",
    is_veg: 1,
    is_featured: 0
  }
];
